name       : haskell-th-utilities
version    : 0.2.0.1
release    : 1
source     :
    - http://hackage.haskell.org/package/th-utilities-0.2.0.1/th-utilities-0.2.0.1.tar.gz : 65c64cee69c0d9bf8d0d5d4590aaea7dcf4177f97818526cbb3fac20901671d6
license    : MIT
component  : programming.haskell
summary    : The 'th-utilities' package provides a number of useful utilities for Template Haskell.
description: |
    The 'th-utilities' package provides a number of useful utilities for Template Haskell.
builddeps  :
    - haskell-cabal-install
    - haskell-primitive
    - haskell-th-orphans
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
