name       : haskell-th-utilities
version    : 0.2.4.0
release    : 3
source     :
    - https://hackage.haskell.org/package/th-utilities-0.2.4.0/th-utilities-0.2.4.0.tar.gz : 340dd6a85d80500fc755bf98ca77ac562ce7755fb126931ab1097a97ba6e71b0
license    : MIT
component  : programming.haskell
summary    : The 'th-utilities' package provides a number of useful utilities for Template Haskell.
description: |
    The 'th-utilities' package provides a number of useful utilities for Template Haskell.
builddeps  :
    - haskell-cabal-install
    - haskell-th-orphans-devel
rundeps    :
    - devel:
        - haskell-th-orphans-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
